version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    ports:
      - '80:8000'
  server-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    ports:
      - '5000:8000'
    volumes:
      - ./src:/app
