version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    ports:
      - '80:8000'
    command: [ "sanic", "server.app", "--host=0.0.0.0", "--fast" ]
  server-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
    ports:
      - '5000:8000'
    command: [ "sanic", "server.app", "--host=0.0.0.0", "--dev" ]
    volumes:
      - ./src:/app
